services:
  # Kasm - Remote Workspaces
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "3000:3000"
      - "$KASM_PORT:443"
    volumes:
      - $DOCKERDIR/appdata/kasm/data:/opt
      - $DOCKERDIR/appdata/kasm/profiles:/profiles #optional
      - /dev/input:/dev/input #optional
      - /run/udev/data:/run/udev/data #optional
    environment:
      TZ: $TZ
      KASM_PORT: 443
      # DOCKER_HUB_USERNAME: USER #optional
      # DOCKER_HUB_PASSWORD: PASS #optional
      # DOCKER_MTU: 1500 #optional
      UMASK: 022
    # DOCKER-LABELS-PLACEHOLDER