services:
  # Nextcloud - Content Collaboration
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$NEXTCLOUD_PORT:80"
    volumes:
      - $DOCKERDIR/appdata/nextcloud:/var/www/html
      - $NEXTCLOUD_FOLDER:/var/www/html/data
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/nextcloud_mariadb_password
      MYSQL_DATABASE: nextcloud
      MYSQL_USER_FILE: /run/secrets/nextcloud_mariadb_user
      MYSQL_HOST: mariadb
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: $REDIS_PASSWORD
      NEXTCLOUD_ADMIN_USER_FILE: /run/secrets/nextcloud_admin_user
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/nextcloud_admin_password
      # NEXTCLOUD_TRUSTED_DOMAINS: SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1
      TRUSTED_PROXIES: 192.168.90.0/24
      # OVERWRITEHOST: SUBDOMAIN-PLACEHOLDER.$DOMAINNAME_1
      OVERWRITEPROTOCOL: https 
    secrets:
      - nextcloud_mariadb_password
      - nextcloud_mariadb_user
      - nextcloud_admin_user
      - nextcloud_admin_password
    # DOCKER-LABELS-PLACEHOLDER